### ISSUE TITLE
Unselect Tutorial/Workshop etc. Button

### ISSUE THREAD

**Issue by harry-hart** [anucssa/anutimetable#44]
Would be nice to have a way to unselect tutorials and switch which one you isolate.

**Comment by pl4nty** [comment]
Thanks for the feedback! Maybe an undo button inside the selected event? That would allow undoing multiple selections, but might make the event too full visually.

The [eventRemove](https://fullcalendar.io/docs/eventRemove) callback receives a `revert` function that might be possible to store, would need to create a state boundary for events though.

**Comment by OliverBalfour** [comment]
A nice touch would be to highlight in grey the other events when you hover over the select button

**Comment by pl4nty** [comment]
`revert` hasn't worked, so we might have to look at refactoring EventSource handling. Per-selection sources (eg COMP1130_TutA) would allow refetch() to reload events (effectively undo). Alternatively, we could mutate events and sources in state directly, rather than using the limited calendar API.

A hover effect should be pretty easy - since we only need visible events, filtering on getEvents() will be sufficient.

**Comment by pl4nty** [comment]
@OliverBalfour strange, the FC is built on typescript so I've had no troubles with jump to typedef or intellisense. But their API is definitely limiting - I'm just concerned we might hit some nasty state bugs if we take over state management, and/or performance if FC maintains an internal state deep copy.

Re packing into extendedProps - that was my first idea and I completely forgot, thanks for reminding! I think you're right, it should work. I remember looking at an Event:: event-to-object serialiser and addEvent, and I've already implemented the packing side for `revert`s (just a revertSelect array). Query param would be fine, cause it just calls `selectOccurrence` which handles the select onClick. Would have to ensure addEvent can re-associate with the corresponding eventSource though, otherwise course removal would break.

**Comment by pl4nty** [comment]
Lmk if you want to work on this today, and I'll push what I have for packing `revert`. Shouldn't be too bad, but I was running into a race condition when initialising revertSelection with setExtendedProp

**Comment by OliverBalfour** [comment]
I'm at work today so I'll see if I can squeeze it in tonight. If CalendarApi proves tricky I'll just use some state instead - we change the event state very infrequently so I don't think performance will take much of a bit, but I'll do some basic testing to make sure it's still usable on a low end phone

**Comment by pl4nty** [comment]
Ah, I'm happy to PR this arvo then since I'm already half-finished. Reckon a [sm button](https://react-bootstrap-v4.netlify.app/components/buttons/#sizes) would be suitable? Or could use an <a>

**Comment by pl4nty** [comment]
Cool, I was hesitant on the button too because of clutter on mobile etc. Might not get to it tonight tho, had to work til 8 🤔

**Comment by OliverBalfour** [comment]
All good, I'm on it!

**Comment by OliverBalfour** [comment]
Fixed in #55, awaiting review and merge. I added small "Choose"/"Reset" link buttons. I didn't add the highlight feature as I thought the buttons were good enough UX for now
