### ISSUE TITLE
Add an unhide feature

### ISSUE THREAD

**Issue by Tharu-silva** [anucssa/anutimetable#97]
Currently once you hide a lecture/tut block there is no way to unhide that without removing the class then adding it again.

**Comment by Talon2267** [comment]
HI @Tharu-silva there is actually a way to unhide it - in the very bottom right corner there is an option. It's just very hard to access given the settings icon. Here is an image of what you should see. (also on dark mode its almost impossible to see it since that text is black for it).
![Screen Shot 2022-01-19 at 6 37 57 pm](https://user-images.githubusercontent.com/97817211/150085367-343a96b8-0ab4-4df6-bd87-e211651e3fb2.png)
![Screen Shot 2022-01-19 at 6 38 15 pm](https://user-images.githubusercontent.com/97817211/150085373-c46329b0-277e-4058-9950-aafc6c86e2c0.png)

**Comment by pl4nty** [comment]
@Talon2267 thanks, I had no idea that existed - we should definitely make it more obvious.

@OliverBalfour want to take this one?

**Comment by OliverBalfour** [comment]
Yeah should go in the FAB. I'll aim to get it done within the week, my schedule is packed

**Comment by OliverBalfour** [comment]
Fixed in #103, awaiting merge

**Comment by pl4nty** [comment]
Thanks @OliverBalfour! @Tharu-silva the hide button is now available inside the settings button in the bottom right.
